# S3 Flood Configuration Example
# Copy this file to config.yaml and update with your settings

s3_urls:
  - http://localhost:9000        # S3 endpoint URLs (can be multiple for cluster mode)
access_key: YOUR_ACCESS_KEY     # Your S3 access key
secret_key: YOUR_SECRET_KEY     # Your S3 secret key
bucket_name: test-bucket        # Name of the bucket to use for testing
cluster_mode: false             # Enable cluster mode for multiple endpoints
parallel_threads: 5             # Number of parallel threads for operations

# File groups configuration
file_groups:
  small:
    max_size_mb: 100            # Maximum size for small files (in MB)
    count: 100                  # Number of small files to create
  medium:
    max_size_mb: 5120           # Maximum size for medium files (in MB)
    count: 50                   # Number of medium files to create
  large:
    max_size_mb: 20480          # Maximum size for large files (in MB)
    count: 10                   # Number of large files to create

# Test cycle configuration
infinite_loop: true             # Run tests in an infinite loop
cycle_delay_seconds: 15         # Delay between test cycles (in seconds)

# Test files location
test_files_directory: "./s3_temp_files"  # Directory for temporary test files

# Algorithm selection (not directly configurable in file, selected at runtime)
# Available algorithms:
# - traditional: Write-Read-Delete (default)
# - infinite_write: Continuous write operations without deletion